apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todolist
        image: todo-list:before-otel
        imagePullPolicy: Never # Build with docker desktop
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        - name: DbConnectionString
          value: Server=tcp:mssql-svc; Database=TodoListDb; User Id=sa; Password=$(DB_PASSWORD);
---
apiVersion: v1
kind: Service
metadata:
  name: todo-list-svc
spec:
  selector:
    app: todo-list
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
  type: NodePort
