apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-item-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-item
  template:
    metadata:
      labels:
        app: todo-item
    spec:
      containers:
      - name: todoitem
        image: todo-item:before-otel
        imagePullPolicy: Never # Build with docker desktop
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-item-svc
spec:
  selector:
    app: todo-item
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
